name: Update OHA Data
on:
  schedule:
    - cron: '0 */6 * * *' # Alle 6 Stunden
  workflow_dispatch: # Erlaubt manuelles Starten

jobs:
  build:
    runs-as-ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Download OHA Data
        run: |
          curl -L "https://oha.to/mediaurl-catalog.json" -o mediaurl-catalog.json

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add mediaurl-catalog.json
          git commit -m "Update OHA data" || exit 0
          git push
